=== uo277440/sew_5/xml/rutas.dtd
<!ELEMENT rutas (ruta*)>
<!ELEMENT ruta (tipoRuta,medioTransporte,fechaInicio,horaInicio,personasAdecuadas,coordenadasInicio,referencias,hitos,recomendacion)>
<!ELEMENT hito (coordenadas,distanciaAnterior,fotoHitos,videosHito)>
<!ELEMENT tipoRuta (#PCDATA)>
<!ELEMENT medioTransporte (#PCDATA)>
<!ELEMENT fechaInicio (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT personasAdecuadas (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT direccionInicio (#PCDATA)>
<!ELEMENT coordenadasInicio (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT coordenadas (#PCDATA)>
<!ELEMENT distanciaAnterior (#PCDATA)>
<!ELEMENT fotoHitos (fotoHito+)>
<!ELEMENT fotoHito (#PCDATA)>
<!ELEMENT videosHito (videoHito*)>
<!ELEMENT videoHito (#PCDATA)>
<!ATTLIST ruta
	lugarInicio CDATA #REQUIRED
	direccionInicio CDATA #REQUIRED
	descripcion CDATA #REQUIRED
	agencia CDATA #REQUIRED
	duracion CDATA #REQUIRED
	nombre CDATA #REQUIRED
	>
<!ATTLIST hito
	nombre CDATA #REQUIRED
	descripcion CDATA #REQUIRED>

=== uo277440/sew_5/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta nombre="a" lugarInicio="lugarInicio" direccionInicio="direccion" descripcion="descripcion" agencia="agencia" duracion="dura">
        <tipoRuta>Silvestre</tipoRuta>
        <medioTransporte>Coche</medioTransporte>
        <fechaInicio>12/12/12</fechaInicio>
        <horaInicio>12:00</horaInicio>
        <personasAdecuadas>No ni√±os</personasAdecuadas>
        <coordenadasInicio>1;38</coordenadasInicio>
        <referencias>
            <referencia>Una referencia</referencia>
            <referencia>Otra referencia</referencia>
        </referencias>
        <hitos>
            <hito nombre="super hito" descripcion="un hito interesante">
                <coordenadas>1;38</coordenadas>
                <distanciaAnterior>4km</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>una foto</fotoHito>
                    <fotoHito>otra foto</fotoHito>
                </fotoHitos>
                <videosHito>
                    <videoHito>Un video</videoHito>
                    <videoHito>Otro video</videoHito>
                </videosHito>
            </hito>
           
        </hitos>
        <recomendacion>6</recomendacion>
    </ruta>
</rutas>
