=== uo277440/sew_5/xml/Nueva carpeta/rutas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/rutas" elementFormDefault="qualified" targetNamespace="http://tempuri.org/rutas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tipoRuta" />
				<xs:element ref="medioTransporte" />
				<xs:element ref="fechaInicio" />
				<xs:element ref="horaInicio" />
				<xs:element ref="personasAdecuadas" />
				<xs:element ref="coordenadasInicio" />
				<xs:element ref="referencias" />
				<xs:element ref="hitos" />
				<xs:element ref="recomendacion" />
			</xs:sequence>
			<xs:attribute name="lugarInicio" type="xs:string" use="required" />
			<xs:attribute name="direccionInicio" type="xs:string" use="required" />
			<xs:attribute name="descripcion" type="xs:string" use="required" />
			<xs:attribute name="agencia" type="xs:string" use="required" />
			<xs:attribute name="duracion" type="xs:duration" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
				<xs:element ref="distanciaAnterior" />
				<xs:element ref="fotoHitos" />
				<xs:element ref="videosHito" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="descripcion" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="tipoRuta" type="xs:string" />
	<xs:element name="medioTransporte" type="xs:string" />
	<xs:element name="fechaInicio" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	<xs:element name="duracion" type="xs:duration" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:nonNegativeInteger">
				<xs:minInclusive value="0" />
				<xs:maxInclusive value="10" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="personasAdecuadas" type="xs:string" />
	<xs:element name="lugarInicio" type="xs:string" />
	<xs:element name="direccionInicio" type="xs:string" />
	<xs:element name="coordenadasInicio" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="longitud" type="xs:float"/>
				<xs:element name="latitud" type="xs:float"/>
				<xs:element name="altitud" type="xs:float"/>
			</xs:sequence>
		</xs:complexType>

	</xs:element>
	<xs:element name="distanciaAnterior" type="xs:string" />
	<xs:element name="fotoHitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotoHito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotoHito" type="xs:string" />
	<xs:element name="videosHito">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="videoHito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="videoHito" type="xs:string" />
</xs:schema>

=== uo277440/sew_5/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://tempuri.org/rutas"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tempuri.org/rutas ./rutas.xsd">
    <ruta nombre="Ruta Safari en Maasai Mara" lugarInicio="lugarInicio" direccionInicio="direccion" descripcion="Una emocionante ruta de safari en la Reserva Nacional de Maasai Mara." agencia="agencia" duracion="P1Y7M29DT12H">
        <tipoRuta>Silvestre</tipoRuta>
        <medioTransporte>Coche</medioTransporte>
        <fechaInicio>2018-10-20</fechaInicio>
        <horaInicio>12:30:00</horaInicio>
        <personasAdecuadas>Amantes de la naturaleza y la vida silvestre</personasAdecuadas>
        <coordenadasInicio>
            <longitud>35.091013</longitud>
            <latitud>-1.407593</latitud>
            <altitud>1542</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Mas%C3%A1i_Mara</referencia>
            <referencia>https://www.rhinoafrica.com/es/destinos/reserva-nacional-masai-mara/21753</referencia>
            <referencia>https://www.aventuraafrica.com/paises/kenia/destinos/masai-mara</referencia>
        </referencias>
        <hitos>
            <hito nombre="Rio Mara" descripcion="Importante curso de agua que añade dramatismo a la Gran Migración y ofrece escenarios pintorescos para la observación de vida silvestre.">
                <coordenadas>
                    <longitud>35.232635</longitud>
                    <latitud>-1.510389</latitud>
                    <altitud>1595</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">60</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/rio_mara.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
            <hito nombre="Gran Migracion" descripcion="Espectáculo único donde millones de ñus y cebras migran en busca de pastos frescos en la Reserva Nacional de Maasai Mara">
                <coordenadas>
                    <longitud>35.131388</longitud>
                    <latitud>-1.426111</latitud>
                    <altitud>1420</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">219</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/gran_migracion.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
            <hito nombre="Colina Oloololo" descripcion="Punto panorámico que brinda vistas impresionantes de la Reserva Nacional de Maasai Mara, ideal para apreciar la extensión de la fauna y la belleza natural">
                <coordenadas>
                    <longitud>35.095244</longitud>
                    <latitud>-1.439476</latitud>
                    <altitud>1539</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">82</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/oloololo.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
           
        </hitos>
        <recomendacion>6</recomendacion>
    </ruta>
    <ruta nombre="Ruta en el Bosque Aberdare" lugarInicio="lugarInicio" direccionInicio="direccion" descripcion="Una caminata serena a través del bosque Aberdare." agencia="agencia" duracion="P1Y7M29DT12H">
        <tipoRuta>Silvestre</tipoRuta>
        <medioTransporte>A pie</medioTransporte>
        <fechaInicio>2018-10-20</fechaInicio>
        <horaInicio>12:30:00</horaInicio>
        <personasAdecuadas>Aficionados a la caminata y la observación de aves</personasAdecuadas>
        <coordenadasInicio>
            <longitud>36.451683</longitud>
            <latitud>0.566818</latitud>
            <altitud>1983</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia>https://www.alltrails.com/es/wales/rhondda-cynon-taf/aberdare/forest</referencia>
            <referencia>https://samakisafaris.com/parque-nacional-aberdare</referencia>
            <referencia>https://udare.es/parque-nacional-aberdare-en-kenia/</referencia>
        </referencias>
        <hitos>
            <hito nombre="Arbol gigante Gatamaiyu" descripcion="Majestuoso árbol en el Bosque Aberdare, destacado por su grandiosidad y significado en la región">
                <coordenadas>
                    <longitud>36.430723</longitud>
                    <latitud>0.543462</latitud>
                    <altitud>1973</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">85</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/arbol.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
            <hito nombre="Cascada Karuru" descripcion="Hermosa cascada en medio del Bosque Aberdare, ofreciendo un paisaje sereno y una experiencia refrescante">
                <coordenadas>
                    <longitud>36.396042</longitud>
                    <latitud>0.560789</latitud>
                    <altitud>1894</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">110</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/karuru.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
            <hito nombre="Refugio de Pesca de Treetops" descripcion="Punto de interés en el bosque, conocido por ofrecer experiencias únicas de observación de vida silvestre desde plataformas elevadas">
                <coordenadas>
                    <longitud>36.460897</longitud>
                    <latitud>0.546110</latitud>
                    <altitud>1978</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">140</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/pesca.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
           
        </hitos>
        <recomendacion>6</recomendacion>
    </ruta>
    <ruta nombre="Ruta en Bicicleta por el Lago Naivasha" lugarInicio="lugarInicio" direccionInicio="direccion" descripcion="Un recorrido escénico en bicicleta alrededor del hermoso lago Naivasha." agencia="agencia" duracion="P1Y7M29DT12H">
        <tipoRuta>Silvestre</tipoRuta>
        <medioTransporte>Coche</medioTransporte>
        <fechaInicio>2018-10-20</fechaInicio>
        <horaInicio>12:30:00</horaInicio>
        <personasAdecuadas>No niños</personasAdecuadas>
        <coordenadasInicio>
            <longitud>36.429100</longitud>
            <latitud>-0.760347</latitud>
            <altitud>1895</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Lago_Naivasha</referencia>
            <referencia>https://www.safarisentanzania.com/que-ver-y-hacer-en-kenia-en-12-dias/safari-lago-naivasha/</referencia>
            <referencia>https://www.conmochila.com/lago-naivasha</referencia>
        </referencias>
        <hitos>
            <hito nombre="Crescent Island" descripcion="Isla escénica en el Lago Naivasha, hogar de una variedad de vida silvestre y destino popular para paseos en bicicleta">
                <coordenadas>
                    <longitud>36.376713</longitud>
                    <latitud>-0.710248</latitud>
                    <altitud>1888</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">45</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/isla.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
            <hito nombre="Hell's Gate National Park" descripcion="Parque nacional en la orilla del lago, conocido por sus imponentes formaciones rocosas y actividades recreativas, como ciclismo y senderismo">
                <coordenadas>
                    <longitud>36.359298</longitud>
                    <latitud>-0.901683</latitud>
                    <altitud>2095</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">80</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/parque.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
            <hito nombre="Piedras Fischer's Tower" descripcion="Formación rocosa distintiva en el parque, atractiva para escaladores y amantes de la geología">
                <coordenadas>
                    <longitud>36.353431</longitud>
                    <latitud>-0.741916</latitud>
                    <altitud>1880</altitud>
                </coordenadas>
                <distanciaAnterior unidad="km">95</distanciaAnterior>
                <fotoHitos>
                    <fotoHito>./multimedia/fotosRutas/torre.jpg</fotoHito>
                </fotoHitos>
                <videosHito>
                </videosHito>
            </hito>
           
        </hitos>
        <recomendacion>6</recomendacion>
    </ruta>
</rutas>
